PhoneBook.WebApp/Models/ContactInformationViewModel.cs
namespace PhoneBook.WebApp.Models
{
    public class ContactInformationViewModel
    {
        public int PersonUUID { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Location { get; set; }
    }
}

PhoneBook.WebApp/Models/ErrorViewModel.cs
namespace PhoneBook.WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PhoneBook.WebApp/Models/PersonViewModel.cs
namespace PhoneBook.WebApp.Models
{
    public class PersonViewModel
    {
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
    }
}

PhoneBook.WebApp/Models/ServiceModel/ContactInformation.cs
namespace PhoneBook.WebApp.Models.ServiceModel
{
    public class ContactInformation
    {
        public int Id { get; set; }
        public int PersonUUID { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Location { get; set; }
    }
}

PhoneBook.WebApp/Models/ServiceModel/Person.cs
namespace PhoneBook.WebApp.Models.ServiceModel
{
    public class Person
    {
        public int UUID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
    }
}

PhoneBook.WebApp/Models/ServiceModel/Report.cs
namespace PhoneBook.WebApp.Models.ServiceModel
{
    public class Report
    {
        public int UUID { get; set; }
        public DateTime ReportCreatedDate { get; set; }
        public string ReportStatus { get; set; }
        public string ReportPath { get; set; }
    }
}

PhoneBook.WebApp/Models/ServiceModel/ResponseDataModel.cs
namespace PhoneBook.WebApp.Models.ServiceModel
{
    public class ResponseDataModel<T>: ResponseModel
    {
        public T Data { get; set; }
    }
}

PhoneBook.WebApp/Models/ServiceModel/ResponseModel.cs
namespace PhoneBook.WebApp.Models.ServiceModel
{
    public class ResponseModel
    {
        public bool Success { get; set; }
        public string Message { get; set; }
    }
}

PhoneBook.WebApp/Controllers/ContactInformationsController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneBook.WebApp.Models;
using PhoneBook.WebApp.Services.Abstact;

namespace PhoneBook.WebApp.Controllers
{
    public class ContactInformationsController : Controller
    {
        private readonly IContactInformationService _contactInformationService;

        public ContactInformationsController(IContactInformationService contactInformationService)
        {
            _contactInformationService = contactInformationService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List(int id)
        {
            var result = _contactInformationService.GetAllByPersonId(id);
            return View(result.Data);
        }

        [HttpGet]
        public IActionResult Create(int id)
        {
            var contactInformationViewModel = new ContactInformationViewModel { PersonUUID = id };
            return View(contactInformationViewModel);
        }

        [HttpPost]
        public IActionResult Create(ContactInformationViewModel contactInformationViewModel)
        {
            if (ModelState.IsValid)
            {
                var result = _contactInformationService.Add(contactInformationViewModel);
                if (result.Success)
                    return Redirect($"/ContactInformations/List/{contactInformationViewModel.PersonUUID}");
            }
            return View();
        }

        public IActionResult Delete(int id)
        {
            if (ModelState.IsValid)
            {
                var result = _contactInformationService.Delete(id);
                if (result.Success)
                    return Redirect("/Persons/Index");
            }
            return View();
        }
    }
}

PhoneBook.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneBook.WebApp.Models;
using System.Diagnostics;

namespace PhoneBook.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PhoneBook.WebApp/Controllers/PersonsController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneBook.WebApp.Models;
using PhoneBook.WebApp.Services.Abstact;

namespace PhoneBook.WebApp.Controllers
{
    public class PersonsController : Controller
    {
        private readonly IPersonService _personService;

        public PersonsController(IPersonService personService)
        {
            _personService = personService;
        }

        public IActionResult Index()
        {
            var personList = _personService.GetAll();
            return View(personList.Data);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(PersonViewModel personViewModel)
        {
            if (ModelState.IsValid)
            {
                var result = _personService.Add(personViewModel);
                if (result.Success)
                    return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int id)
        {
            if (ModelState.IsValid)
            {
                var result = _personService.Delete(id);
                if (result.Success)
                    return RedirectToAction("Index");
            }
            return View();
        }


    }
}

PhoneBook.WebApp/Controllers/ReportsController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneBook.WebApp.Services.Abstact;

namespace PhoneBook.WebApp.Controllers
{
    public class ReportsController : Controller
    {
        private readonly IReportService _reportService;
        public ReportsController(IReportService reportService)
        {
            _reportService = reportService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult List()
        {
            var result = _reportService.GetAll();
            return View(result.Data);
        }

        public IActionResult ReportDownload(int id)
        {
            if (ModelState.IsValid)
            {
                var result = _reportService.ReportDownload(id);
                return File(result, "application/xlsx", $"Konum_Raporu_{DateTime.Now.Ticks}.xlsx");
            }
            return View();
        }

        public IActionResult RequestReport()
        {
            if (ModelState.IsValid)
            {
                var result = _reportService.RequestReport();
                if (result)
                    return RedirectToAction("List");
            }
            return View();
        }
    }
}

PhoneBook.WebApp/Views/ContactInformations/Create.cshtml
@model ContactInformationViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<form asp-controller="ContactInformations" asp-action="Create" method="post">
    <input type="hidden" name="personUUID" value="@Model.PersonUUID" />
    <div class="form-group">
        <label for="phone">Telefon</label>
        <input type="text" class="form-control" id="phone" name="phone" placeholder="Konum giriniz.">
    </div>

    <div class="form-group">
        <label for="email">Email</label>
        <input type="text" class="form-control" id="email" name="email" placeholder="Konum giriniz.">
    </div>

    <div class="form-group">
        <label for="location">Konum</label>
        <input type="text" class="form-control" id="location" name="location" placeholder="Konum giriniz.">
    </div>

    </br>
    <button type="submit" class="btn btn-primary">Kaydet</button>
</form>

PhoneBook.WebApp/Views/ContactInformations/List.cshtml
@using PhoneBook.WebApp.Models.ServiceModel;
@model List<ContactInformation>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Telefon</th>
            <th scope="col">Email</th>
            <th scope="col">Konum</th>
            <th scope="col">İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var contactInformation in Model)
        {
            <tr>
                <th scope="row">@contactInformation.Id</th>
                <td>@contactInformation.Phone</td>
                <td>@contactInformation.Email</td>
                <td>@contactInformation.Location</td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <a href="/ContactInformations/Delete/@contactInformation.Id" type="button" class="btn btn-danger">Sil</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

PhoneBook.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PhoneBook.WebApp/Views/Persons/Create.cshtml
@model PersonViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<form asp-controller="Persons" asp-action="Create" method="post">
    <div class="form-group">
        <label for="name">Adı</label>
        <input type="text" class="form-control" id="name" name="name" placeholder="Adı giriniz.">
    </div>

    <div class="form-group">
        <label for="lastName">Soyadı</label>
        <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Soyadı giriniz.">
    </div>

    <div class="form-group">
        <label for="company">Firma</label>
        <input type="text" class="form-control" id="company" name="company" placeholder="Firma giriniz.">
    </div>

    </br>
    <button type="submit" class="btn btn-primary">Kaydet</button>
</form>

PhoneBook.WebApp/Views/Persons/Index.cshtml
@using PhoneBook.WebApp.Models.ServiceModel;
@model List<Person>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Adı</th>
            <th scope="col">Soyadı</th>
            <th scope="col">Firma</th>
            <th scope="col">İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var person in Model)
        {
            <tr>
                <th scope="row">@person.UUID</th>
                <td>@person.Name</td>
                <td>@person.LastName</td>
                <td>@person.Company</td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <a href="/Persons/Delete/@person.UUID" type="button" class="btn btn-danger">Sil</a>
                        <a href="/ContactInformations/List/@person.UUID" type="button" class="btn btn-info">İletişim Bilgileri</a>
                        <a href="/ContactInformations/Create/@person.UUID" type="button" class="btn btn-success">İletişim Bilgisi Ekle</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

PhoneBook.WebApp/Views/Reports/List.cshtml
@using PhoneBook.WebApp.Models.ServiceModel;
@model List<Report>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<a href="/Reports/RequestReport" type="button" class="btn btn-success">Rapor Oluştur</a>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Rapor Tarihi</th>
            <th scope="col">Rapor Durumu</th>
            <th scope="col">İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var report in Model)
        {
            <tr>
                <th scope="row">@report.UUID</th>
                <td>@report.ReportCreatedDate</td>
                <td>@report.ReportStatus</td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        @if (report.ReportStatus == "Tamamlandı")
                        {
                            <a href="/Reports/ReportDownload/@report.UUID" type="button" class="btn btn-success">İndir</a>
                        }
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

PhoneBook.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhoneBook.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PhoneBook.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Telefon Defteri</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Persons" asp-action="Create">Kişi Oluştur</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Persons" asp-action="Index">Kişi Listesi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reports" asp-action="List">Raporlar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Telefon Defteri - Ömer Besent
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>